"""rhwp._rhwp — PyO3 Rust 확장의 타입 스텁.

``_Document`` 는 Rust thin core 로, 직접 사용하지 않는다. 사용자-대면 API 는
:class:`rhwp.Document` (Python wrapper) 와 :func:`rhwp.parse` 이다.
``rhwp.document`` 가 본 타입을 ``_inner`` 로 감싸고 메서드를 위임한다.
"""

from rhwp.ir.nodes import HwpDocument

__all__ = [
    "_Document",
    "rhwp_core_version",
    "version",
]

def version() -> str:
    """rhwp Python 패키지 버전."""
    ...

def rhwp_core_version() -> str:
    """rhwp Rust 코어 버전."""
    ...

class _Document:
    """Rust thin core — Python wrapper 전용. 사용자는 :class:`rhwp.Document` 사용."""

    source_uri: str | None
    section_count: int
    paragraph_count: int
    page_count: int

    def __init__(self, path: str) -> None: ...
    @classmethod
    def from_bytes(cls, data: bytes, *, source_uri: str | None = None) -> _Document: ...
    def extract_text(self) -> str: ...
    def paragraphs(self) -> list[str]: ...
    def render_svg(self, page: int) -> str: ...
    def render_all_svg(self) -> list[str]: ...
    def export_svg(self, output_dir: str, prefix: str | None = None) -> list[str]: ...
    def render_pdf(self) -> bytes: ...
    def export_pdf(self, output_path: str) -> int: ...
    def to_ir(self) -> HwpDocument: ...
    def to_ir_json(self, *, indent: int | None = None) -> str: ...
    def bytes_for_image_id(self, bin_data_id: int) -> bytes | None: ...
    def __repr__(self) -> str: ...
